FROM node:22-bookworm-slim AS build

WORKDIR /app

COPY package.json package-lock.json ./
RUN npm ci && npm install --global @vscode/vsce

COPY . ./
RUN npm run compile

FROM build AS package

RUN vsce package --out /tmp/piste.vsix

FROM scratch AS artifact

COPY --from=package /tmp/piste.vsix /piste.vsix

FROM build AS publish

CMD ["vsce", "publish"]
